name: Build Unsigned IPA and Upload

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-upload:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
          pod repo update
          pod install

      - name: Build Unsigned IPA
        run: |
          xcodebuild \
            -workspace "Stay.xcworkspace" \
            -scheme "Stay" \
            -configuration "Release" \
            -sdk "iphoneos" \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="" \
            PROVISIONING_PROFILE_SPECIFIER=""

          mkdir -p Payload
          cp -R build/Build/Products/Release-iphoneos/Stay.app Payload/
          zip -r Stay.zip Payload
          mv Stay.zip Stay.ipa
          ls -lh Stay.ipa

      - name: Upload IPA to GoFile
        uses: toiletpuppy/gofile@New
        with:
          files: "Stay.ipa"

